name: belajar_anak
description: Bermain Sambil Belajar untuk Anak Usia 4-6 Tahun
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0        # Audio suara huruf/hewan/sfx (PRD D.1)
  google_fonts: ^6.0.0        # Nunito font (PRD C.3)
  shared_preferences: ^2.0.0  # Simpan skor lokal
  flutter_tts: 3.8.0
  provider: ^6.0.0            # State management (PRD D.3)
  go_router: ^13.0.0          # Navigasi antar screen (PRD D.4)
  confetti: ^0.7.0            # Animasi konfeti kuis
  flutter_animate: ^4.0.0     # Animasi bounce/fade/slide
  lottie: ^3.0.0              # Animasi JSON (opsional maskot)

flutter:
  uses-material-design: true
  assets:
    - assets/audio/huruf/
    - assets/audio/angka/
    - assets/audio/hewan/
    - assets/audio/warna/
    - assets/audio/sfx/
    - assets/images/hewan/
    - assets/images/icons/
# Font Nunito diambil via package google_fonts (PRD C.3)
